import Database from "better-sqlite3";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

export const cleanTag=(s:string)=>s.trim().replace(/^#+/,"").replace(/\s+/g," ").slice(0,80);
const hash=(s:string)=>crypto.createHash("sha256").update(s).digest("hex");
const token=()=>crypto.randomBytes(24).toString("base64url");
const isHeading=(s:string)=>{const t=s.trim(),ls=t.split("\n").filter(Boolean);return !!t&&ls.length<=2&&t.length<=30&&!/[。！？.!?：:；;]/.test(t)};
export function splitParagraphsSmart(content:string){
  const a=content.replace(/\r\n?/g,"\n").split(/\n\s*\n+/).map(x=>x.trim()).filter(Boolean),out:string[]=[];
  for(let i=0;i<a.length;i++){if(a[i+1]&&isHeading(a[i])){out.push(`${a[i]}\n${a[i+1]}`);i++;}else out.push(a[i]);} return out;
}
type Upload={originalName:string;mimeType:string;buffer:Buffer};
const baseUrl=()=>{const x=(process.env.PUBLIC_BASE_URL||"").trim()||(process.env.RAILWAY_PUBLIC_DOMAIN?`https://${process.env.RAILWAY_PUBLIC_DOMAIN}`:"");return x.replace(/\/$/,"")};

export function createArchive(dbPath:string){
  const abs=path.resolve(dbPath),dir=path.dirname(abs),uploads=path.join(dir,"uploads");fs.mkdirSync(uploads,{recursive:true});
  const db=new Database(abs);db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");db.exec(fs.readFileSync(path.resolve("schema.sql"),"utf8"));
  const cols=(db.prepare("PRAGMA table_info(stories)").all() as any[]).map(x=>x.name);if(!cols.includes("raw_content"))db.exec("ALTER TABLE stories ADD COLUMN raw_content TEXT");
  const imgUrl=(id:number)=>`${baseUrl()}/image/${id}`;
  const act=(actor:number|null,story:number|null,p:number|null,action:string,detail:any=null)=>db.prepare("INSERT INTO activities(actor_id,story_id,paragraph_id,action,detail) VALUES(?,?,?,?,?)").run(actor,story,p,action,detail==null?null:JSON.stringify(detail));
  const tags=(story:number)=>(db.prepare("SELECT t.name FROM story_tags st JOIN tags t ON t.id=st.tag_id WHERE st.story_id=? ORDER BY t.name").all(story) as any[]).map(x=>x.name);
  const images=(story:number)=>(db.prepare("SELECT id,slot_no,original_name,storage_path,mime_type,bytes,created_at FROM story_images WHERE story_id=? ORDER BY slot_no").all(story) as any[]).map(x=>({...x,image_url:imgUrl(x.id)}));
  const image=(id:number)=>{const x=db.prepare("SELECT * FROM story_images WHERE id=?").get(id) as any;if(!x)throw new Error("image_id 不存在。");return {...x,abs_path:path.join(uploads,x.storage_path),image_url:imgUrl(id)}};
  function actorFromToken(t:string){const a=db.prepare("SELECT id,display_name,window_label FROM actors WHERE token_hash=?").get(hash(t)) as any;if(!a)throw new Error("actor_token 无效；请先 register_actor。");db.prepare("UPDATE actors SET last_seen_at=datetime('now') WHERE id=?").run(a.id);return a;}
  function registerActor(displayName:string,windowLabel?:string){const t=token(),r=db.prepare("INSERT INTO actors(display_name,window_label,token_hash) VALUES(?,?,?)").run(displayName.trim().slice(0,80),windowLabel?.trim().slice(0,120)||null,hash(t));return {actor_id:Number(r.lastInsertRowid),display_name:displayName.trim(),window_label:windowLabel?.trim()||null,actor_token:t};}
  function setTags(story:number,list:string[]){db.prepare("DELETE FROM story_tags WHERE story_id=?").run(story);for(const raw of list){const t=cleanTag(raw);if(!t)continue;db.prepare("INSERT OR IGNORE INTO tags(name) VALUES(?)").run(t);const x=db.prepare("SELECT id FROM tags WHERE name=? COLLATE NOCASE").get(t) as any;db.prepare("INSERT OR IGNORE INTO story_tags(story_id,tag_id) VALUES(?,?)").run(story,x.id);}}
  function addImages(story:number,list:Upload[]=[]){let n=Number((db.prepare("SELECT COALESCE(MAX(slot_no),0) n FROM story_images WHERE story_id=?").get(story) as any).n);for(const f of list){n++;const ext=path.extname(f.originalName).slice(0,12),name=`${story}-${n}-${Date.now()}-${crypto.randomBytes(3).toString("hex")}${ext}`;fs.writeFileSync(path.join(uploads,name),f.buffer);db.prepare("INSERT INTO story_images(story_id,slot_no,original_name,storage_path,mime_type,bytes) VALUES(?,?,?,?,?,?)").run(story,n,f.originalName||`image-${n}`,name,f.mimeType||"application/octet-stream",f.buffer.length);}return images(story);}
  function parse(raw:string,story:number){const im=new Map(images(story).map((x:any)=>[x.slot_no,x])),out:any[]=[];const re=/\[\[image:(\d+)(?:\|([^\]]+))?\]\]/g;let last=0,m:RegExpExecArray|null;const text=(s:string)=>splitParagraphsSmart(s).forEach(v=>out.push({type:"text",text:v}));while((m=re.exec(raw))){text(raw.slice(last,m.index));const x=im.get(Number(m[1]));if(x)out.push({type:"image",image_id:(x as any).id,caption:m[2]?.trim()||null});else out.push({type:"text",text:m[0]});last=re.lastIndex;}text(raw.slice(last));if(!out.length)for(const x of images(story))out.push({type:"image",image_id:x.id,caption:null});return out;}
  function rebuild(story:number,raw:string){
    const old=db.prepare("SELECT id,content FROM paragraphs WHERE story_id=?").all(story) as any[],pool=new Map<string,number[]>();for(const p of old){if(!pool.has(p.content))pool.set(p.content,[]);pool.get(p.content)!.push(p.id);db.prepare("UPDATE paragraphs SET paragraph_no=? WHERE id=?").run(-p.id,p.id);}db.prepare("DELETE FROM content_blocks WHERE story_id=?").run(story);
    const used=new Set<number>(),blocks=parse(raw,story),ins=db.prepare("INSERT INTO content_blocks(story_id,block_no,block_type,paragraph_id,image_id,caption) VALUES(?,?,?,?,?,?)");let pn=0,bn=0;
    for(const b of blocks){bn++;if(b.type==="image"){ins.run(story,bn,"image",null,b.image_id,b.caption);continue;}pn++;let id=pool.get(b.text)?.shift();if(id){db.prepare("UPDATE paragraphs SET paragraph_no=? WHERE id=?").run(pn,id);}else{const r=db.prepare("INSERT INTO paragraphs(story_id,paragraph_no,content) VALUES(?,?,?)").run(story,pn,b.text);id=Number(r.lastInsertRowid);db.prepare("INSERT INTO paragraph_fts(rowid,content) VALUES(?,?)").run(id,b.text);}used.add(id!);ins.run(story,bn,"text",id,null,null);}
    for(const p of old)if(!used.has(p.id)){db.prepare("DELETE FROM paragraph_fts WHERE rowid=?").run(p.id);db.prepare("DELETE FROM paragraphs WHERE id=?").run(p.id);}db.prepare("DELETE FROM story_fts WHERE rowid=?").run(story);const s=db.prepare("SELECT title,summary FROM stories WHERE id=?").get(story) as any;db.prepare("INSERT INTO story_fts(rowid,title,summary) VALUES(?,?,?)").run(story,s.title,s.summary||"");return {paragraph_count:pn,block_count:bn,image_count:images(story).length};
  }
  for(const s of db.prepare("SELECT id,raw_content FROM stories").all() as any[]){const c=Number((db.prepare("SELECT COUNT(*) n FROM content_blocks WHERE story_id=?").get(s.id) as any).n);if(c)continue;const ps=db.prepare("SELECT id,paragraph_no,content FROM paragraphs WHERE story_id=? ORDER BY paragraph_no").all(s.id) as any[];if(!s.raw_content&&ps.length){const raw=ps.map(x=>x.content).join("\n\n");db.prepare("UPDATE stories SET raw_content=? WHERE id=?").run(raw,s.id);}ps.forEach((p,i)=>db.prepare("INSERT INTO content_blocks(story_id,block_no,block_type,paragraph_id) VALUES(?,?,\"text\",?)").run(s.id,i+1,p.id));}
  function uploadStory(x:{title:string;rawContent?:string;content?:string;summary?:string;category?:string;sourceNote?:string;tags?:string[];images?:Upload[]}){if(!x.title.trim())throw new Error("标题不能为空。");const raw=x.rawContent??x.content??"";const tx=db.transaction(()=>{const r=db.prepare("INSERT INTO stories(title,summary,category,source_note,raw_content) VALUES(?,?,?,?,?)").run(x.title.trim(),x.summary?.trim()||null,x.category?.trim()||"其他",x.sourceNote?.trim()||null,raw),id=Number(r.lastInsertRowid);addImages(id,x.images);setTags(id,x.tags||[]);const z=rebuild(id,raw);act(null,id,null,"upload_story",z);return {story_id:id,...z};});return tx();}
  function updateStory(x:{storyId:number;title:string;rawContent?:string;content?:string;summary?:string;category?:string;sourceNote?:string;tags?:string[];images?:Upload[]}){const raw=x.rawContent??x.content??"";const tx=db.transaction(()=>{if(!db.prepare("SELECT 1 FROM stories WHERE id=?").get(x.storyId))throw new Error("story_id 不存在。");addImages(x.storyId,x.images);db.prepare("UPDATE stories SET title=?,summary=?,category=?,source_note=?,raw_content=?,updated_at=datetime('now') WHERE id=?").run(x.title.trim(),x.summary?.trim()||null,x.category?.trim()||"其他",x.sourceNote?.trim()||null,raw,x.storyId);setTags(x.storyId,x.tags||[]);const z=rebuild(x.storyId,raw);act(null,x.storyId,null,"edit_story",z);return {story_id:x.storyId,...z};});return tx();}
  const meta=(id:number)=>{const s=db.prepare("SELECT * FROM stories WHERE id=?").get(id) as any;if(!s)throw new Error("story_id 不存在。");if(!s.raw_content)s.raw_content=(db.prepare("SELECT content FROM paragraphs WHERE story_id=? ORDER BY paragraph_no").all(id) as any[]).map(x=>x.content).join("\n\n");return {...s,tags:tags(id),images:images(id)}};
  function listStories(x:{tag?:string;category?:string;limit?:number;offset?:number}){const lim=Math.min(x.limit||30,100),off=x.offset||0;let a=db.prepare("SELECT id,title,summary,category,source_note,created_at,updated_at FROM stories WHERE (? IS NULL OR category=?) ORDER BY id DESC LIMIT ? OFFSET ?").all(x.category||null,x.category||null,lim*3,off) as any[];if(x.tag){const t=cleanTag(x.tag).toLowerCase();a=a.filter(s=>tags(s.id).some(v=>v.toLowerCase()===t));}return a.slice(0,lim).map(s=>({...s,tags:tags(s.id),image_count:images(s.id).length}));}
  function searchPassages(x:{query:string;tags?:string[];category?:string;limit?:number}){const lim=Math.min(x.limit||12,40),want=(x.tags||[]).map(cleanTag).map(v=>v.toLowerCase());const a=db.prepare("SELECT p.id paragraph_id,p.story_id,p.paragraph_no,s.title,s.category,s.summary,snippet(paragraph_fts,0,'【','】','…',36) snippet,bm25(paragraph_fts) score FROM paragraph_fts JOIN paragraphs p ON p.id=paragraph_fts.rowid JOIN stories s ON s.id=p.story_id WHERE paragraph_fts MATCH ? AND (? IS NULL OR s.category=?) ORDER BY score LIMIT ?").all(x.query.trim(),x.category||null,x.category||null,lim*5) as any[];return a.filter(r=>want.every(w=>tags(r.story_id).some(t=>t.toLowerCase()===w))).slice(0,lim).map(r=>({...r,tags:tags(r.story_id)}));}
  function searchStories(x:{query:string;tags?:string[];category?:string;limit?:number}){const lim=Math.min(x.limit||10,30),want=(x.tags||[]).map(cleanTag).map(v=>v.toLowerCase());const a=db.prepare("SELECT s.id story_id,s.title,s.summary,s.category,s.source_note,snippet(story_fts,0,'【','】','…',18) title_hit,snippet(story_fts,1,'【','】','…',28) summary_hit,bm25(story_fts) score FROM story_fts JOIN stories s ON s.id=story_fts.rowid WHERE story_fts MATCH ? AND (? IS NULL OR s.category=?) ORDER BY score LIMIT ?").all(x.query.trim(),x.category||null,x.category||null,lim*4) as any[];return a.filter(r=>want.every(w=>tags(r.story_id).some(t=>t.toLowerCase()===w))).slice(0,lim).map(r=>({...r,tags:tags(r.story_id),image_count:images(r.story_id).length}));}
  const comments=db.prepare("SELECT c.id comment_id,c.body,c.reply_to,c.created_at,a.display_name actor,a.window_label,pa.display_name reply_to_actor,pc.body reply_to_body FROM comments c JOIN actors a ON a.id=c.actor_id LEFT JOIN comments pc ON pc.id=c.reply_to LEFT JOIN actors pa ON pa.id=pc.actor_id WHERE c.paragraph_id=? ORDER BY c.id");
  function outline(id:number){const s=meta(id),ps=db.prepare("SELECT id paragraph_id,paragraph_no,CASE WHEN length(content)>120 THEN substr(content,1,120)||'…' ELSE content END preview FROM paragraphs WHERE story_id=? ORDER BY paragraph_no").all(id) as any[],bs=db.prepare("SELECT block_no,block_type,paragraph_id,image_id,caption FROM content_blocks WHERE story_id=? ORDER BY block_no").all(id);return {...s,paragraph_count:ps.length,paragraphs:ps,blocks:bs};}
  function readParagraphs(id:number,start:number,end:number,inc=true){if(end<start)[start,end]=[end,start];end=Math.min(end,start+39);return {story:meta(id),paragraphs:(db.prepare("SELECT id paragraph_id,paragraph_no,content FROM paragraphs WHERE story_id=? AND paragraph_no BETWEEN ? AND ? ORDER BY paragraph_no").all(id,start,end) as any[]).map(p=>({...p,comments:inc?comments.all(p.paragraph_id):undefined}))};}
  function readAllParagraphs(id:number,inc=true){return {story:meta(id),paragraphs:(db.prepare("SELECT id paragraph_id,paragraph_no,content FROM paragraphs WHERE story_id=? ORDER BY paragraph_no").all(id) as any[]).map(p=>({...p,comments:inc?comments.all(p.paragraph_id):undefined}))};}
  function readStoryBlocks(id:number,start:number,end:number,inc=true){if(end<start)[start,end]=[end,start];end=Math.min(end,start+59);const a=db.prepare("SELECT cb.id block_id,cb.block_no,cb.block_type,cb.caption,p.id paragraph_id,p.paragraph_no,p.content,si.id image_id,si.slot_no,si.original_name,si.mime_type,si.bytes FROM content_blocks cb LEFT JOIN paragraphs p ON p.id=cb.paragraph_id LEFT JOIN story_images si ON si.id=cb.image_id WHERE cb.story_id=? AND cb.block_no BETWEEN ? AND ? ORDER BY cb.block_no").all(id,start,end) as any[];return {story:meta(id),blocks:a.map(r=>r.block_type==="text"?{...r,comments:inc?comments.all(r.paragraph_id):undefined}:{...r,image_url:imgUrl(r.image_id)})};}
  function readAllBlocks(id:number,inc=true){const n=Number((db.prepare("SELECT COALESCE(MAX(block_no),0) n FROM content_blocks WHERE story_id=?").get(id) as any).n);return readStoryBlocks(id,1,Math.max(n,1),inc);}
  function getStoryDocument(id:number){const s=outline(id);return {...s,blocks:(s.blocks as any[]).map(b=>b.block_type==="image"?{...b,...image(b.image_id)}:b)};}
  function addTags(actorToken:string,story:number,list:string[]){const a=actorFromToken(actorToken),added:string[]=[];for(const raw of list){const t=cleanTag(raw);if(!t)continue;db.prepare("INSERT OR IGNORE INTO tags(name) VALUES(?)").run(t);const x=db.prepare("SELECT id,name FROM tags WHERE name=? COLLATE NOCASE").get(t) as any;const r=db.prepare("INSERT OR IGNORE INTO story_tags(story_id,tag_id,added_by) VALUES(?,?,?)").run(story,x.id,a.id);if(r.changes){added.push(x.name);act(a.id,story,null,"add_tag",{tag:x.name});}}return {story_id:story,added,tags:tags(story)};}
  function comment(actorToken:string,pid:number,body:string,replyTo?:number){const a=actorFromToken(actorToken),p=db.prepare("SELECT story_id,paragraph_no FROM paragraphs WHERE id=?").get(pid) as any;if(!p)throw new Error("paragraph_id 不存在。");let parent:any=null;if(replyTo){parent=db.prepare("SELECT c.paragraph_id,a.display_name actor FROM comments c JOIN actors a ON a.id=c.actor_id WHERE c.id=?").get(replyTo) as any;if(!parent||parent.paragraph_id!==pid)throw new Error("reply_to 必须属于同一段落。");}const r=db.prepare("INSERT INTO comments(paragraph_id,actor_id,body,reply_to) VALUES(?,?,?,?)").run(pid,a.id,body.trim(),replyTo||null),id=Number(r.lastInsertRowid);act(a.id,p.story_id,pid,replyTo?"reply_comment":"comment_paragraph",{comment_id:id,paragraph_no:p.paragraph_no,reply_to:replyTo||null,reply_to_actor:parent?.actor||null,body:body.trim()});return {comment_id:id,story_id:p.story_id,paragraph_no:p.paragraph_no,reply_to:replyTo||null};}
  function activityFeed(x:{limit?:number;storyId?:number;actorName?:string}){const w:string[]=[],a:any[]=[];if(x.storyId){w.push("ac.story_id=?");a.push(x.storyId)}if(x.actorName){w.push("aa.display_name=?");a.push(x.actorName)}a.push(Math.min(x.limit||30,100));return db.prepare(`SELECT ac.id activity_id,ac.action,ac.detail,ac.created_at,aa.display_name actor,aa.window_label,s.id story_id,s.title,p.paragraph_no FROM activities ac LEFT JOIN actors aa ON aa.id=ac.actor_id LEFT JOIN stories s ON s.id=ac.story_id LEFT JOIN paragraphs p ON p.id=ac.paragraph_id ${w.length?"WHERE "+w.join(" AND "):""} ORDER BY ac.id DESC LIMIT ?`).all(...a);}
  const listTags=(limit=100)=>db.prepare("SELECT t.name,COUNT(st.story_id) story_count FROM tags t LEFT JOIN story_tags st ON st.tag_id=t.id GROUP BY t.id ORDER BY story_count DESC,t.name LIMIT ?").all(Math.min(limit,300));
  const listActors=(limit=100)=>db.prepare("SELECT a.id,a.display_name,a.window_label,a.created_at,a.last_seen_at,COUNT(DISTINCT c.id) comments,COUNT(DISTINCT st.story_id) tagged_stories FROM actors a LEFT JOIN comments c ON c.actor_id=a.id LEFT JOIN story_tags st ON st.added_by=a.id GROUP BY a.id ORDER BY a.id DESC LIMIT ?").all(Math.min(limit,200));
  function deleteStory(id:number){if(!db.prepare("SELECT 1 FROM stories WHERE id=?").get(id))return false;for(const x of images(id)){try{fs.unlinkSync(path.join(uploads,x.storage_path))}catch{}}for(const p of db.prepare("SELECT id FROM paragraphs WHERE story_id=?").all(id) as any[])db.prepare("DELETE FROM paragraph_fts WHERE rowid=?").run(p.id);db.prepare("DELETE FROM story_fts WHERE rowid=?").run(id);db.prepare("DELETE FROM stories WHERE id=?").run(id);return true;}
  return {db,registerActor,uploadStory,updateStory,listStories,searchPassages,searchStories,storyOutline:outline,getStoryForEdit:meta,getStoryDocument,readParagraphs,readAllParagraphs,readStoryBlocks,readAllBlocks,addTags,comment,activityFeed,listTags,listActors,listStoryImages:images,getImageById:image,deleteStory};
}
export type Archive=ReturnType<typeof createArchive>;
